name: "✨ New Feature"
description: "For submitting new features or enhancements."
body:
  - type: markdown
    attributes:
      value: "Thanks for proposing a new feature! Please fill out the following to help us understand the request."

  - type: textarea
    attributes:
      label: "What is the new feature?"
      description: "Describe the feature you would like to add."

  - type: textarea
    attributes:
      label: "Why is this feature needed?"
      description: "Explain why this feature would be valuable to the project."

  - type: checkboxes
    id: input1
    attributes:
      label: "Testing"
      options:
        - label: "I have considered how to test this feature."
        - label: "I have added tests for this feature."

  - type: textarea
    attributes:
      label: "How will this feature be used?"
      description: "Describe how the feature will be used or integrated into the project."

  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any additional context, related links, or design documents."

  - type: dropdown
    attributes:
      label: "Which area is affected by this feature?"
      options:
        - Core
        - CLI
        - Plugins
        - Documentation
        - Tests
        - Other
    validations:
      required: true
